modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPL-3.0-only"

[[mods]]
 modId = "starlight"
 version = "1.1.2+forge.1cda73c"
 displayName = "Starlight"
 authors = "Spottedleaf"
 description = '''Rewrites the light engine to fix lighting performance and lighting errors'''
 logoFile = "logo.png"
 displayURL = "https://www.curseforge.com/minecraft/mc-mods/starlight-forge"

 [[dependencies.starlight]]
  modId = "forge"
  mandatory = true
  versionRange = "[46,)"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.starlight]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.20,1.21)"
  ordering = "NONE"
  side = "BOTH"